export const JOES_STORES = [
  {
    id: "greenwich-village",
    name: "Greenwich Village",
    neighborhood: "Original",
    address: "7 Carmine Street, New York, NY 10014",
    phone: "(212) 366-1182",
    city: "New York",
    capacity_pizzas: 140,
    van_available: false,
    timezone: "America/New_York",
  },
  {
    id: "times-square",
    name: "Times Square",
    neighborhood: "Midtown",
    address: "1435 Broadway, New York, NY 10018",
    phone: "(646) 559-4878",
    city: "New York",
    capacity_pizzas: 160,
    van_available: false,
    timezone: "America/New_York",
  },
  {
    id: "union-square",
    name: "Union Square",
    neighborhood: "Union Square",
    address: "150 East 14th Street, New York, NY 10003",
    phone: "(212) 388-9474",
    city: "New York",
    capacity_pizzas: 130,
    van_available: false,
    timezone: "America/New_York",
  },
  {
    id: "fulton-street",
    name: "Fulton Street",
    neighborhood: "Financial District",
    address: "124 Fulton Street, New York, NY 10038",
    phone: "(212) 267-0860",
    city: "New York",
    capacity_pizzas: 125,
    van_available: false,
    timezone: "America/New_York",
  },
  {
    id: "williamsburg",
    name: "Williamsburg",
    neighborhood: "Brooklyn",
    address: "216 Bedford Avenue, Brooklyn, NY 11249",
    phone: "(718) 388-2216",
    city: "Brooklyn",
    capacity_pizzas: 120,
    van_available: true,
    timezone: "America/New_York",
  },
  {
    id: "miami-wynwood",
    name: "Miami Wynwood",
    neighborhood: "Wynwood / Dock",
    address: "234 NW 25th Street, Miami, FL 33127",
    phone: "(786) 230-1441",
    city: "Miami",
    capacity_pizzas: 110,
    van_available: true,
    timezone: "America/New_York",
  },
  {
    id: "miami-beach",
    name: "Miami Beach",
    neighborhood: "Miami Beach",
    address: "1674 Meridian Ave, Miami Beach, FL 33139",
    phone: "",
    city: "Miami Beach",
    capacity_pizzas: 115,
    van_available: false,
    timezone: "America/New_York",
  },
  {
    id: "boston",
    name: "Boston",
    neighborhood: "Fenway",
    address: "1359 Boylston Street, Boston, MA 02215",
    phone: "(617) 936-4464",
    city: "Boston",
    capacity_pizzas: 118,
    van_available: false,
    timezone: "America/New_York",
  },
  {
    id: "cambridge",
    name: "Cambridge",
    neighborhood: "Harvard Square",
    address: "3 Brattle Street, Cambridge, MA 02138",
    phone: "(857) 226-4942",
    city: "Cambridge",
    capacity_pizzas: 110,
    van_available: false,
    timezone: "America/New_York",
  },
  {
    id: "ann-arbor",
    name: "Ann Arbor",
    neighborhood: "Campus",
    address: "1107 S University Ave, Ann Arbor, MI 48104",
    phone: "(734) 213-5625",
    city: "Ann Arbor",
    capacity_pizzas: 105,
    van_available: false,
    timezone: "America/New_York",
  },
];

export const INVENTORY_CATALOG = [
  { sku: "dough", label: "Dough balls", unit: "lbs", par: 80 },
  { sku: "flour", label: "Flour", unit: "lbs", par: 120 },
  { sku: "water", label: "Filtered water", unit: "gal", par: 40 },
  { sku: "cheese", label: "Mozzarella", unit: "lbs", par: 50 },
  { sku: "sauce", label: "Tomato sauce", unit: "gal", par: 18 },
  { sku: "pepperoni", label: "Pepperoni", unit: "lbs", par: 20 },
  { sku: "boxes", label: "Pizza boxes", unit: "count", par: 400 },
  { sku: "oil", label: "Olive oil", unit: "gal", par: 8 },
];

export const ROLE_POOL = [
  "cashier",
  "pizzaiolo",
  "shift_lead",
  "delivery",
  "prep",
];

export const FIRST_NAMES = [
  "Mia",
  "Luis",
  "Sofia",
  "Andre",
  "Priya",
  "Jordan",
  "Elena",
  "Carlos",
  "Sam",
  "Rosa",
  "Nina",
  "Omar",
];
